#############################################################################
# Makefile for building: QUI.app/Contents/MacOS/QUI
# Generated by qmake (2.01a) (Qt 4.4.0) on: Fri Mar 27 17:11:53 2009
# Project:  QUI.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.4/mkspecs/macx-g++ -macx -o Makefile QUI.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_KEYWORDS -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -arch ppc -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -arch ppc -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.4/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/Library/Frameworks/QtSql.framework/Versions/4/Headers -I/usr/include/QtSql -I/usr/include -I. -I/usr/local/include/boost-1_35 -I. -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch ppc
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtSql -framework QtGui -framework Carbon -framework AppKit -framework QtCore -lz -lm -framework ApplicationServices
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.3

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.C \
		OptionDatabaseForm.C \
		Option.C \
		OptionDatabase.C \
		OptionEditors.C \
		Conditions.C \
		Actions.C \
		InputDialogLogic.C \
		InputDialogSlots.C \
		InitializeQChemLogic.C \
		Job.C \
		Qui.C \
		FileDisplay.C \
		KeywordSection.C \
		ReadInput.C \
		RemSection.C \
		Preferences.C \
		MoleculeSection.C \
		InputDialog.C \
		GeometryConstraint.C \
		OptSection.C \
		ExternalChargesSection.C \
		LJParametersSection.C \
		FindDialog.C \
		Process.C \
		InputDialogMenu.C \
		ProcessQChemKill.C \
		getpids.C moc_OptionDatabaseForm.cpp \
		moc_OptionEditors.cpp \
		moc_InputDialog.cpp \
		moc_QtNode.cpp \
		moc_FileDisplay.cpp \
		moc_Preferences.cpp \
		moc_GeometryConstraint.cpp \
		moc_FindDialog.cpp \
		moc_Process.cpp \
		qrc_QUI.cpp
OBJECTS       = main.o \
		OptionDatabaseForm.o \
		Option.o \
		OptionDatabase.o \
		OptionEditors.o \
		Conditions.o \
		Actions.o \
		InputDialogLogic.o \
		InputDialogSlots.o \
		InitializeQChemLogic.o \
		Job.o \
		Qui.o \
		FileDisplay.o \
		KeywordSection.o \
		ReadInput.o \
		RemSection.o \
		Preferences.o \
		MoleculeSection.o \
		InputDialog.o \
		GeometryConstraint.o \
		OptSection.o \
		ExternalChargesSection.o \
		LJParametersSection.o \
		FindDialog.o \
		Process.o \
		InputDialogMenu.o \
		ProcessQChemKill.o \
		getpids.o \
		moc_OptionDatabaseForm.o \
		moc_OptionEditors.o \
		moc_InputDialog.o \
		moc_QtNode.o \
		moc_FileDisplay.o \
		moc_Preferences.o \
		moc_GeometryConstraint.o \
		moc_FindDialog.o \
		moc_Process.o \
		qrc_QUI.o
DIST          = /usr/local/Qt4.4/mkspecs/common/unix.conf \
		/usr/local/Qt4.4/mkspecs/common/mac.conf \
		/usr/local/Qt4.4/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.4/mkspecs/qconfig.pri \
		/usr/local/Qt4.4/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.4/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.4/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.4/mkspecs/features/debug.prf \
		/usr/local/Qt4.4/mkspecs/features/default_post.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/ppc.prf \
		/usr/local/Qt4.4/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.4/mkspecs/features/qt.prf \
		/usr/local/Qt4.4/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.4/mkspecs/features/moc.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.4/mkspecs/features/resources.prf \
		/usr/local/Qt4.4/mkspecs/features/uic.prf \
		/usr/local/Qt4.4/mkspecs/features/yacc.prf \
		/usr/local/Qt4.4/mkspecs/features/lex.prf \
		QUI.pro
QMAKE_TARGET  = QUI
DESTDIR       = 
TARGET        = QUI.app/Contents/MacOS/QUI

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		ppc \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile QUI.app/Contents/PkgInfo QUI.app/Contents/Info.plist QUI.app/Contents/Resources/qchem.png $(TARGET)

$(TARGET): ui_OptionDatabaseForm.h ui_OptionListEditor.h ui_OptionNumberEditor.h ui_FileDisplay.h ui_QuiMainWindow.h ui_PreferencesBrowser.h ui_GeometryConstraintDialog.h ui_FindDialog.h ui_ProcessMonitor.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) QUI.app/Contents/MacOS/ || $(MKDIR) QUI.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QUI.pro  /usr/local/Qt4.4/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.4/mkspecs/common/unix.conf \
		/usr/local/Qt4.4/mkspecs/common/mac.conf \
		/usr/local/Qt4.4/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.4/mkspecs/qconfig.pri \
		/usr/local/Qt4.4/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.4/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.4/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.4/mkspecs/features/debug.prf \
		/usr/local/Qt4.4/mkspecs/features/default_post.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/ppc.prf \
		/usr/local/Qt4.4/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.4/mkspecs/features/qt.prf \
		/usr/local/Qt4.4/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.4/mkspecs/features/moc.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.4/mkspecs/features/resources.prf \
		/usr/local/Qt4.4/mkspecs/features/uic.prf \
		/usr/local/Qt4.4/mkspecs/features/yacc.prf \
		/usr/local/Qt4.4/mkspecs/features/lex.prf \
		/Library/Frameworks/QtSql.framework/QtSql.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl \
		/Library/Frameworks/QtGui.framework/QtGui.prl
	$(QMAKE) -spec /usr/local/Qt4.4/mkspecs/macx-g++ -macx -o Makefile QUI.pro
/usr/local/Qt4.4/mkspecs/common/unix.conf:
/usr/local/Qt4.4/mkspecs/common/mac.conf:
/usr/local/Qt4.4/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.4/mkspecs/qconfig.pri:
/usr/local/Qt4.4/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.4/mkspecs/features/qt_config.prf:
/usr/local/Qt4.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.4/mkspecs/features/default_pre.prf:
/usr/local/Qt4.4/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.4/mkspecs/features/debug.prf:
/usr/local/Qt4.4/mkspecs/features/default_post.prf:
/usr/local/Qt4.4/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.4/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.4/mkspecs/features/mac/ppc.prf:
/usr/local/Qt4.4/mkspecs/features/warn_on.prf:
/usr/local/Qt4.4/mkspecs/features/qt.prf:
/usr/local/Qt4.4/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.4/mkspecs/features/moc.prf:
/usr/local/Qt4.4/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.4/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.4/mkspecs/features/resources.prf:
/usr/local/Qt4.4/mkspecs/features/uic.prf:
/usr/local/Qt4.4/mkspecs/features/yacc.prf:
/usr/local/Qt4.4/mkspecs/features/lex.prf:
/Library/Frameworks/QtSql.framework/QtSql.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
/Library/Frameworks/QtGui.framework/QtGui.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.4/mkspecs/macx-g++ -macx -o Makefile QUI.pro

QUI.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) QUI.app/Contents || $(MKDIR) QUI.app/Contents 
	@$(DEL_FILE) QUI.app/Contents/PkgInfo
	@echo "APPL????" >QUI.app/Contents/PkgInfo
QUI.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) QUI.app/Contents || $(MKDIR) QUI.app/Contents 
	@$(DEL_FILE) QUI.app/Contents/Info.plist
	@sed -e "s,@ICON@,qchem.png,g" -e "s,@EXECUTABLE@,QUI,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.4/mkspecs/macx-g++/Info.plist.app >QUI.app/Contents/Info.plist
QUI.app/Contents/Resources/qchem.png: resources/icons/qchem.png
	@$(CHK_DIR_EXISTS) QUI.app/Contents/Resources/ || $(MKDIR) QUI.app/Contents/Resources/ 
	@$(DEL_FILE) QUI.app/Contents/Resources/qchem.png
	@$(COPY_FILE) resources/icons/qchem.png QUI.app/Contents/Resources/qchem.png
dist: 
	@$(CHK_DIR_EXISTS) .tmp/QUI1.0.0 || $(MKDIR) .tmp/QUI1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QUI1.0.0/ && $(COPY_FILE) --parents OptionDatabaseForm.h OptionEditors.h InputDialog.h Node.h QtNode.h Register.h OptionDatabase.h Conditions.h Option.h Actions.h Qui.h Job.h FileDisplay.h KeywordSection.h RemSection.h Preferences.h MoleculeSection.h GeometryConstraint.h OptSection.h ExternalChargesSection.h LJParametersSection.h FindDialog.h Process.h .tmp/QUI1.0.0/ && $(COPY_FILE) --parents QUI.qrc .tmp/QUI1.0.0/ && $(COPY_FILE) --parents main.C OptionDatabaseForm.C Option.C OptionDatabase.C OptionEditors.C Conditions.C Actions.C InputDialogLogic.C InputDialogSlots.C InitializeQChemLogic.C Job.C Qui.C FileDisplay.C KeywordSection.C ReadInput.C RemSection.C Preferences.C MoleculeSection.C InputDialog.C GeometryConstraint.C OptSection.C ExternalChargesSection.C LJParametersSection.C FindDialog.C Process.C InputDialogMenu.C ProcessQChemKill.C getpids.C .tmp/QUI1.0.0/ && $(COPY_FILE) --parents OptionDatabaseForm.ui OptionListEditor.ui OptionNumberEditor.ui FileDisplay.ui QuiMainWindow.ui PreferencesBrowser.ui GeometryConstraintDialog.ui FindDialog.ui ProcessMonitor.ui .tmp/QUI1.0.0/ && (cd `dirname .tmp/QUI1.0.0` && $(TAR) QUI1.0.0.tar QUI1.0.0 && $(COMPRESS) QUI1.0.0.tar) && $(MOVE) `dirname .tmp/QUI1.0.0`/QUI1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QUI1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r QUI.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_OptionDatabaseForm.cpp moc_OptionEditors.cpp moc_InputDialog.cpp moc_QtNode.cpp moc_FileDisplay.cpp moc_Preferences.cpp moc_GeometryConstraint.cpp moc_FindDialog.cpp moc_Process.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_OptionDatabaseForm.cpp moc_OptionEditors.cpp moc_InputDialog.cpp moc_QtNode.cpp moc_FileDisplay.cpp moc_Preferences.cpp moc_GeometryConstraint.cpp moc_FindDialog.cpp moc_Process.cpp
moc_OptionDatabaseForm.cpp: ui_OptionDatabaseForm.h \
		OptionDatabaseForm.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ OptionDatabaseForm.h -o moc_OptionDatabaseForm.cpp

moc_OptionEditors.cpp: ui_OptionNumberEditor.h \
		ui_OptionListEditor.h \
		OptionEditors.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ OptionEditors.h -o moc_OptionEditors.cpp

moc_InputDialog.cpp: ui_QuiMainWindow.h \
		OptionRegister.h \
		Register.h \
		QuiString.h \
		QtNode.h \
		Node.h \
		Logic.h \
		InputDialog.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ InputDialog.h -o moc_InputDialog.cpp

moc_QtNode.cpp: Node.h \
		Logic.h \
		QtNode.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ QtNode.h -o moc_QtNode.cpp

moc_FileDisplay.cpp: ui_FileDisplay.h \
		FileDisplay.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ FileDisplay.h -o moc_FileDisplay.cpp

moc_Preferences.cpp: ui_PreferencesBrowser.h \
		Preferences.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Preferences.h -o moc_Preferences.cpp

moc_GeometryConstraint.cpp: ui_GeometryConstraintDialog.h \
		GeometryConstraint.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ GeometryConstraint.h -o moc_GeometryConstraint.cpp

moc_FindDialog.cpp: ui_FindDialog.h \
		FindDialog.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ FindDialog.h -o moc_FindDialog.cpp

moc_Process.cpp: ui_ProcessMonitor.h \
		Process.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ Process.h -o moc_Process.cpp

compiler_rcc_make_all: qrc_QUI.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_QUI.cpp
qrc_QUI.cpp: QUI.qrc \
		resources/icons/qchem.png \
		resources/icons/minus.png \
		resources/icons/qchem.icns \
		resources/icons/plus.png
	/Developer/Tools/Qt/rcc -name QUI QUI.qrc -o qrc_QUI.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_OptionDatabaseForm.h ui_OptionListEditor.h ui_OptionNumberEditor.h ui_FileDisplay.h ui_QuiMainWindow.h ui_PreferencesBrowser.h ui_GeometryConstraintDialog.h ui_FindDialog.h ui_ProcessMonitor.h
compiler_uic_clean:
	-$(DEL_FILE) ui_OptionDatabaseForm.h ui_OptionListEditor.h ui_OptionNumberEditor.h ui_FileDisplay.h ui_QuiMainWindow.h ui_PreferencesBrowser.h ui_GeometryConstraintDialog.h ui_FindDialog.h ui_ProcessMonitor.h
ui_OptionDatabaseForm.h: OptionDatabaseForm.ui
	/Developer/Tools/Qt/uic OptionDatabaseForm.ui -o ui_OptionDatabaseForm.h

ui_OptionListEditor.h: OptionListEditor.ui
	/Developer/Tools/Qt/uic OptionListEditor.ui -o ui_OptionListEditor.h

ui_OptionNumberEditor.h: OptionNumberEditor.ui
	/Developer/Tools/Qt/uic OptionNumberEditor.ui -o ui_OptionNumberEditor.h

ui_FileDisplay.h: FileDisplay.ui
	/Developer/Tools/Qt/uic FileDisplay.ui -o ui_FileDisplay.h

ui_QuiMainWindow.h: QuiMainWindow.ui
	/Developer/Tools/Qt/uic QuiMainWindow.ui -o ui_QuiMainWindow.h

ui_PreferencesBrowser.h: PreferencesBrowser.ui
	/Developer/Tools/Qt/uic PreferencesBrowser.ui -o ui_PreferencesBrowser.h

ui_GeometryConstraintDialog.h: GeometryConstraintDialog.ui
	/Developer/Tools/Qt/uic GeometryConstraintDialog.ui -o ui_GeometryConstraintDialog.h

ui_FindDialog.h: FindDialog.ui
	/Developer/Tools/Qt/uic FindDialog.ui -o ui_FindDialog.h

ui_ProcessMonitor.h: ProcessMonitor.ui
	/Developer/Tools/Qt/uic ProcessMonitor.ui -o ui_ProcessMonitor.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.C OptionDatabaseForm.h \
		ui_OptionDatabaseForm.h \
		InputDialog.h \
		ui_QuiMainWindow.h \
		OptionRegister.h \
		Register.h \
		QuiString.h \
		QtNode.h \
		Node.h \
		Logic.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.C

OptionDatabaseForm.o: OptionDatabaseForm.C OptionDatabaseForm.h \
		ui_OptionDatabaseForm.h \
		OptionDatabase.h \
		Option.h \
		OptionEditors.h \
		ui_OptionNumberEditor.h \
		ui_OptionListEditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OptionDatabaseForm.o OptionDatabaseForm.C

Option.o: Option.C Option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Option.o Option.C

OptionDatabase.o: OptionDatabase.C OptionDatabase.h \
		Option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OptionDatabase.o OptionDatabase.C

OptionEditors.o: OptionEditors.C OptionEditors.h \
		ui_OptionNumberEditor.h \
		ui_OptionListEditor.h \
		Option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OptionEditors.o OptionEditors.C

Conditions.o: Conditions.C Conditions.h \
		OptionRegister.h \
		Register.h \
		QuiString.h \
		QtNode.h \
		Node.h \
		Logic.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Conditions.o Conditions.C

Actions.o: Actions.C Actions.h \
		Logic.h \
		OptionRegister.h \
		Register.h \
		QuiString.h \
		QtNode.h \
		Node.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Actions.o Actions.C

InputDialogLogic.o: InputDialogLogic.C OptionRegister.h \
		Register.h \
		QuiString.h \
		QtNode.h \
		Node.h \
		Logic.h \
		Actions.h \
		Conditions.h \
		InputDialog.h \
		ui_QuiMainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InputDialogLogic.o InputDialogLogic.C

InputDialogSlots.o: InputDialogSlots.C GeometryConstraint.h \
		ui_GeometryConstraintDialog.h \
		Preferences.h \
		ui_PreferencesBrowser.h \
		KeywordSection.h \
		OptSection.h \
		ExternalChargesSection.h \
		InputDialog.h \
		ui_QuiMainWindow.h \
		OptionRegister.h \
		Register.h \
		QuiString.h \
		QtNode.h \
		Node.h \
		Logic.h \
		FileDisplay.h \
		ui_FileDisplay.h \
		Option.h \
		Qui.h \
		Job.h \
		OptionDatabase.h \
		Process.h \
		ui_ProcessMonitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InputDialogSlots.o InputDialogSlots.C

InitializeQChemLogic.o: InitializeQChemLogic.C OptionRegister.h \
		Register.h \
		QuiString.h \
		QtNode.h \
		Node.h \
		Logic.h \
		Actions.h \
		Conditions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InitializeQChemLogic.o InitializeQChemLogic.C

Job.o: Job.C Job.h \
		OptionDatabase.h \
		Option.h \
		RemSection.h \
		KeywordSection.h \
		MoleculeSection.h \
		ExternalChargesSection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Job.o Job.C

Qui.o: Qui.C Qui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Qui.o Qui.C

FileDisplay.o: FileDisplay.C FileDisplay.h \
		ui_FileDisplay.h \
		Preferences.h \
		ui_PreferencesBrowser.h \
		FindDialog.h \
		ui_FindDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FileDisplay.o FileDisplay.C

KeywordSection.o: KeywordSection.C RemSection.h \
		KeywordSection.h \
		OptSection.h \
		GeometryConstraint.h \
		ui_GeometryConstraintDialog.h \
		MoleculeSection.h \
		ExternalChargesSection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o KeywordSection.o KeywordSection.C

ReadInput.o: ReadInput.C Job.h \
		Qui.h \
		RemSection.h \
		KeywordSection.h \
		MoleculeSection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ReadInput.o ReadInput.C

RemSection.o: RemSection.C RemSection.h \
		KeywordSection.h \
		Option.h \
		OptionDatabase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RemSection.o RemSection.C

Preferences.o: Preferences.C Preferences.h \
		ui_PreferencesBrowser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Preferences.o Preferences.C

MoleculeSection.o: MoleculeSection.C MoleculeSection.h \
		KeywordSection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MoleculeSection.o MoleculeSection.C

InputDialog.o: InputDialog.C InputDialog.h \
		ui_QuiMainWindow.h \
		OptionRegister.h \
		Register.h \
		QuiString.h \
		QtNode.h \
		Node.h \
		Logic.h \
		OptionDatabase.h \
		Conditions.h \
		Option.h \
		Qui.h \
		Job.h \
		RemSection.h \
		KeywordSection.h \
		LJParametersSection.h \
		Preferences.h \
		ui_PreferencesBrowser.h \
		Process.h \
		ui_ProcessMonitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InputDialog.o InputDialog.C

GeometryConstraint.o: GeometryConstraint.C GeometryConstraint.h \
		ui_GeometryConstraintDialog.h \
		OptSection.h \
		KeywordSection.h \
		Qui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GeometryConstraint.o GeometryConstraint.C

OptSection.o: OptSection.C OptSection.h \
		KeywordSection.h \
		GeometryConstraint.h \
		ui_GeometryConstraintDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OptSection.o OptSection.C

ExternalChargesSection.o: ExternalChargesSection.C ExternalChargesSection.h \
		KeywordSection.h \
		Qui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ExternalChargesSection.o ExternalChargesSection.C

LJParametersSection.o: LJParametersSection.C LJParametersSection.h \
		KeywordSection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LJParametersSection.o LJParametersSection.C

FindDialog.o: FindDialog.C FindDialog.h \
		ui_FindDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FindDialog.o FindDialog.C

Process.o: Process.C FileDisplay.h \
		ui_FileDisplay.h \
		Preferences.h \
		ui_PreferencesBrowser.h \
		Process.h \
		ui_ProcessMonitor.h \
		Qui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Process.o Process.C

InputDialogMenu.o: InputDialogMenu.C InputDialog.h \
		ui_QuiMainWindow.h \
		OptionRegister.h \
		Register.h \
		QuiString.h \
		QtNode.h \
		Node.h \
		Logic.h \
		Preferences.h \
		ui_PreferencesBrowser.h \
		Process.h \
		ui_ProcessMonitor.h \
		Job.h \
		Qui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InputDialogMenu.o InputDialogMenu.C

ProcessQChemKill.o: ProcessQChemKill.C Process.h \
		ui_ProcessMonitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ProcessQChemKill.o ProcessQChemKill.C

getpids.o: getpids.C 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o getpids.o getpids.C

moc_OptionDatabaseForm.o: moc_OptionDatabaseForm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_OptionDatabaseForm.o moc_OptionDatabaseForm.cpp

moc_OptionEditors.o: moc_OptionEditors.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_OptionEditors.o moc_OptionEditors.cpp

moc_InputDialog.o: moc_InputDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_InputDialog.o moc_InputDialog.cpp

moc_QtNode.o: moc_QtNode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QtNode.o moc_QtNode.cpp

moc_FileDisplay.o: moc_FileDisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FileDisplay.o moc_FileDisplay.cpp

moc_Preferences.o: moc_Preferences.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Preferences.o moc_Preferences.cpp

moc_GeometryConstraint.o: moc_GeometryConstraint.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GeometryConstraint.o moc_GeometryConstraint.cpp

moc_FindDialog.o: moc_FindDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FindDialog.o moc_FindDialog.cpp

moc_Process.o: moc_Process.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Process.o moc_Process.cpp

qrc_QUI.o: qrc_QUI.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_QUI.o qrc_QUI.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

